### ISSUE TITLE
Support document theme?

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [peter88213/StyleSwitcher#1]
LibreOffice added support for document theme in [7.6](https://wiki.documentfoundation.org/ReleaseNotes/7.6), since then, I think you could consider add support for importing theme from a template.

**Comment by peter88213** [comment]
I never knew that before. Maybe it's because I'm still using Apache OpenOffice 3.4.1 myself. I have also installed Libreoffice 7.4 for testing extensions. 

As for document themes, I found [this page](https://wiki.documentfoundation.org/Videos/DocumentThemes) with the help of Google, but the explanatory video has disappeared. However, the text indicates that this feature is obviously in an early stage of development. 

If your feature request is not about loading the document template, but only about importing the document themes it contains, this misses the use case of my extension a little. That's why I'm closing the issue now. 

I very much hope that LibreOffice will support the import of document themes in a convenient way so that no extension will be necessary.
